version: '3.8'

services:
  web:
    build:
      context: ./frontend
    ports:
      - "9090:80" # Map localhost:8080 to Nginx's port 80
    networks:
      - donut-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" # Map localhost:5000 to backend port
    networks:
      - donut-network

networks:
  donut-network:
    driver: bridge
