name: Docker Image Build Check

on:
  push:
    branches:
      - compose-branch
  pull_request:
    branches:
      - compose-branch

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Pobranie repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalacja Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Budowanie obrazu Docker
      - name: Build Docker image
        run: docker-compose build
